//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCalculatorApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResourcesEnglish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResourcesEnglish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleCalculatorApp.StringResourcesEnglish", typeof(StringResourcesEnglish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Addition.
        /// </summary>
        internal static string AddChoice {
            get {
                return ResourceManager.GetString("AddChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition is : .
        /// </summary>
        internal static string AddMessage {
            get {
                return ResourceManager.GetString("AddMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which operation you want to perfom ?.
        /// </summary>
        internal static string AskUserMessage {
            get {
                return ResourceManager.GetString("AskUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot divide by Zero.
        /// </summary>
        internal static string DivideByZeroError {
            get {
                return ResourceManager.GetString("DivideByZeroError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Divide.
        /// </summary>
        internal static string DivideChoice {
            get {
                return ResourceManager.GetString("DivideChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division is : .
        /// </summary>
        internal static string DivisionMessage {
            get {
                return ResourceManager.GetString("DivisionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Again : .
        /// </summary>
        internal static string EnterAgain {
            get {
                return ResourceManager.GetString("EnterAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your choice : .
        /// </summary>
        internal static string EnterChoiceMessage {
            get {
                return ResourceManager.GetString("EnterChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter First Number : .
        /// </summary>
        internal static string InputFirstNumberMessage {
            get {
                return ResourceManager.GetString("InputFirstNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Second Number : .
        /// </summary>
        internal static string InputSecondNumberMessage {
            get {
                return ResourceManager.GetString("InputSecondNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Multiply.
        /// </summary>
        internal static string MultiplyChoice {
            get {
                return ResourceManager.GetString("MultiplyChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication is : .
        /// </summary>
        internal static string MultiplyMessage {
            get {
                return ResourceManager.GetString("MultiplyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Subtraction.
        /// </summary>
        internal static string SubtractChoice {
            get {
                return ResourceManager.GetString("SubtractChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtraction is : .
        /// </summary>
        internal static string SubtractionMessage {
            get {
                return ResourceManager.GetString("SubtractionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Input !!!.
        /// </summary>
        internal static string WrongInputMessage {
            get {
                return ResourceManager.GetString("WrongInputMessage", resourceCulture);
            }
        }
    }
}
